FROM node:18-alpine as base

WORKDIR /app
COPY package*.json /
EXPOSE 8000

FROM base as production
ENV NODE_ENV=production
RUN npm ci
COPY . /app
CMD ["node", "src/sender/app.js"]

FROM base as dev
ENV NODE_ENV=development
RUN npm install -g nodemon && npm install
COPY . /
CMD ["nodemon", "src/sender/app.js"]