version: '3'
services:
  db:
    image: mysql:8.0.20
    platform: linux/amd64
    restart: always
    command: --init-file /data/application/init.sql
    env_file: .env.local
    ports:
      - '33062:3306'
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
  sender:
    depends_on:
      - db
    image: sender-api
    build:
      context: ./
      target: dev
      dockerfile: "./Dockerfile.sender"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env.local
  consumer:
    depends_on:
      - db
    image: consumer-api
    build:
      context: ./
      target: dev
      dockerfile: "./Dockerfile.consumer"
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    env_file: .env.local
volumes:
  db: